name: Run Field Guide

on: [push]

jobs:
  generate_images:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install pillow gpt-2-simple tensorflow==1.15

      - name: Get checkpoint
        run: aws s3 cp --recursive s3://jamescoupe-birds/GPT2/checkpoint/ checkpoint

      - name: Let it rip
        run: python3 fg_generator_github.py

      - name: Upload results
        run: aws s3 cp page*.png s3://jamescoupe-birds/output/
